when:
  - event: tag

steps:
  - name: build-and-publish
    image: ghcr.io/astral-sh/uv:python3.14-trixie

    environment:
      UV_PUBLISH_TOKEN:
        from_secret: pypi_token

    commands:
      - |
        set -eu

        TAG="${CI_COMMIT_TAG}"
        VERSION="${TAG#v}"

        echo "Git tag: ${TAG}"
        echo "Package version: ${VERSION}"

        export PACKAGE_VERSION="${VERSION}"

        uv build
        uvx twine check dist/*
        uvx twine upload dist/*
